### PR TITLE
v2.0 

### PR DESCRIPTION
**Pull request by furenberger**
Goal: 
Use Typescript
Rewrite using the https://github.com/homebridge/homebridge-plugin-template 
Add ability to mock (mock-json-server)
Simplify some of the logic (more functional)

- [x] State
- [x] Open
- [x] Close
- [x] First time set up
- [x] Polling for updates
- [x] config.schema.json

@iRayanKhan I am currently running this from my pi via `npm link`.  

image

### CODE REVIEW

**Comment by iRayanKhan** [comment]
Hey @furenberger thank you very much for this PR. I will accept the previous PR first, see if there's anything that this would need to update, then merge. Should be able to merge within a few days.

**Comment by furenberger** [comment]
My only thought is the traffic is so high.  My pi.hole has nearly 74,000 hits since I started running it.  The next most Site has 4000...

Now I honestly hadn’t run the previous version to compare.

Will you try to run this before approving or what else can / should I do to confirm this works?

**Comment by furenberger** [comment]
You could publish it as a beta - i versioned it accordingly.  https://github.com/homebridge/homebridge-plugin-template#publish-package

**Comment by iRayanKhan** [comment]
I'll publish this to beta, but my Pi is freaking out and won't let me git clone anymore, so once that's fixed I can publish again.

**Comment by tonycoco** [comment]
Any chance to merge this? Lots of fixes from what I can see.

**Comment by iRayanKhan** [comment]
Hi, a @beta1 tag will be published today. I had to reset my Mac environment so after reinstalling everything I'll green light a beta, and merge if there's no issues! Sorry for all the delay.

**Comment by iRayanKhan** [comment]
Hey @furenberger,
I'm still a NPM noobie, but when trying to publish your beta, I get this error:

```
> homebridge-chamberlain@2.0.3-beta.1 prepublishOnly .
> npm run lint && npm run build


> homebridge-chamberlain@2.0.3-beta.1 lint /home/pi/homebridge-chamberlain
> eslint src/**.ts

sh: 1: eslint: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! homebridge-chamberlain@2.0.3-beta.1 lint: `eslint src/**.ts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the homebridge-chamberlain@2.0.3-beta.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-24T14_10_47_732Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-chamberlain@2.0.3-beta.1 prepublishOnly: `npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-chamberlain@2.0.3-beta.1 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-24T14_10_47_811Z-debug.log
```


Any advice?

**Comment by furenberger** [comment]
You did a `npm install`?  thats saying it cant find eslint from npm

**Comment by iRayanKhan** [comment]
homebridge-chamberlain@2.0.3-beta.1 tagged rc4, is ready for install & testing.

**Comment by iRayanKhan** [comment]
@furenberger am I able to merge this tomorrow?

**Comment by furenberger** [comment]
oh yeah - let me know if you have issues!

**Comment by furenberger** [comment]
I found it was polling infinitely if someone manually opened the door.  Added a `tries` counter to set the door to the current state after maxTries of polling.

**Comment by iRayanKhan** [comment]
@furenberger since you're on a roll, would you look into adding obstruction detection and/or light controller support?

**Comment by furenberger** [comment]
I’m not sure about a light - is that a different device or is that the
light on the garage opener itself?

I’ll double check but I think obstruct might work?  I know I’ve caused it a
few times this week

**Comment by iRayanKhan** [comment]
Yeah, it's a different device. I wish I could get the lights on the opener added, but the api doesn't show them as a device.

**Comment by iRayanKhan** [comment]
@furenberger how's it going?

Should I merge this and await for a V2.5? Or because I know life crashed for me if it's not possible to the other things someone else could prolly find a way.

**Comment by furenberger** [comment]
I don’t see how to do the lights. 
As far as obstruction my API doesn’t return that as a code but it does track it in the MyQ app.  Unless I am missing something there MyQ may be saving it’s own state?

The only thing I wanted to do still was make sure the config-UI-x template is proper.  It doesn’t seem to work as I expect

**Comment by iRayanKhan** [comment]
I think the myq2 plugin added obstruction detection.

**Comment by iRayanKhan** [comment]
Sweet! would putting the default value in the optionals help, so the user knows what is was?

Also I can merge this in when you're ready.

**Comment by iRayanKhan** [comment]
Thank you @furenberger for the PR. Sadly after discussion with the other MyQ dev, his plugin is more favorable so I'm closing this repo. You're more than happy to make your own repo or use your own fork still, I have transitioned to his plugin.


Thanks for the refactor

- Rayan

**Pull request closed without merging**
