### PR TITLE
Potential fix for #75

### PR DESCRIPTION
**Pull request by dxdc**
There are a few items to note for the `ECONNRESET` issue, which I have been experiencing also.

1. This appears to be (at least, in principle) a problem with `node-fetch`, that might be addressed in an upcoming release. See: https://github.com/node-fetch/node-fetch/issues/309

(The fix appears to be here: https://github.com/node-fetch/node-fetch/pull/768/files)

2. Adding some simple retries to the request may help also. I added a simple version of this using `node-fetch-retry`. There are several other plugins which may be much better though since they offer more configuration options. For example:

- https://github.com/felippemauricio/promise-fn-retry
- https://github.com/jonbern/fetch-retry

However, these may create more 'breaking' functionality depending on individual users node versions.

### CODE REVIEW

**Comment by iRayanKhan** [comment]
Thank you for the PR. Sorry for not replying earlier, I didn't get an email about.

Is there a chance you could define the following door states in this PR and see if that works? 
```
      'stopped': CurrentDoorState.STOPPED,
       'opening': CurrentDoorState.OPENING,
       'closing': CurrentDoorState.CLOSING,
```

Can't test it at the moment, but I hope it would work.

**Comment by DMBlakeley** [comment]
I have installed. Will monitor.

Also added all DoorStates update.

**Comment by dxdc** [comment]
@iRayanKhan I tried your suggestion (see 4a14495) but it crashes the plugin.

```
1|homebrid | [5/21/2020, 10:29:34 AM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
1|homebrid |     at res.text.then.body (/usr/lib/node_modules/homebridge-chamberlain/src/api.js:27:15)
1|homebrid |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dxdc** [comment]
Also, just added a commit (untested) to persist the door state across restarts: 
f9e1027

**Comment by DMBlakeley** [comment]
Also received error from [4a14495](https://github.com/iRayanKhan/homebridge-chamberlain/commit/4a1449552be65cffb389ceec4b79d451b011dc34)

`[5/21/2020, 7:23:54 PM] [Garage Door] Error: invalid response, got HTTP 500: {"code":"500.000","message":"An error occurred while processing the request.","description":"Server Error"}
    at /usr/local/lib/node_modules/homebridge-chamberlain/src/api.js:26:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by iRayanKhan** [comment]
Has there been any additional findings to report? If not I will test this on my main garages, and merge.

**Comment by dxdc** [comment]
Thanks for following up @iRayanKhan. It doesn't work with the merged door states but I didn't continue any further testing (just posted the error msg). I've also found that door states do not update in real time if a non HomeKit route (e.g., button) is used.

**Comment by iRayanKhan** [comment]
Interesting, I will upgrade my main installation later today, and will merge this in. 

Thank you for the contribution!

**Comment by iRayanKhan** [comment]
Hey @dxdc do you mind rebasing this fork to reflect the new api change from earlier? 

If so I'll be happy to merge it, sorry for the delay.

**Comment by dxdc** [comment]
The changes don't work:

> Thanks for following up @iRayanKhan. It doesn't work with the merged door states but I didn't continue any further testing (just posted the error msg). I've also found that door states do not update in real time if a non HomeKit route (e.g., button) is used.

Also, is rebasing needed? I think it should be able to merge as is since that line wasn't modified?

**Comment by dxdc** [comment]
I can revert this commit if you want:  4a14495

**Comment by iRayanKhan** [comment]
Yes, if you could roll back the commit that'd be great.

**Comment by dxdc** [comment]
Done

**Comment by iRayanKhan** [comment]
Was going to merge in today, but seems to be an api change so going to wait for that then merge this. Have you seen anything on your side regarding the api?

**Comment by dxdc** [comment]
@iRayanKhan no I switched to another plugin

**Comment by iRayanKhan** [comment]
Just published with tag ```rc3``` 

The version is 1.6.2-beta.1

**Comment by iRayanKhan** [comment]
Closing: This plugin is now being deprecated. Please use [this](https://github.com/hjdhjd/homebridge-myq) plugin.

**Pull request closed without merging**
